/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIChat: typeof import('./components/AIChat.vue')['default']
    Card3dEffect: typeof import('./components/Card3dEffect.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    CounterAnimation: typeof import('./components/CounterAnimation.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EnhancedButton: typeof import('./components/EnhancedButton.vue')['default']
    ImporterExporter: typeof import('./components/ImporterExporter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundControl: typeof import('./components/SoundControl.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
